# -*- coding: utf-8 -*-
from django.conf import settings

AUTH0_CALLBACK_URL = settings.AUTH0_CALLBACK_URL or 'auth_callback'
